server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb
  h2:
    console:
      enabled: true
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: passw0rd
    realmImportFile: keycloak-realm.json
